language: php

matrix:
  fast_finish: true
  include:
  # Minimum supported dependencies with min and max PHP version
  - php: 7.2
    env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
  - php: 7.1
  - php: 7.0
  - php: 7.3
  - php: 7.4
  - php: 7.3
    env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpunit ${PHPUNIT_FLAGS}
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require phpstan/phpstan; ./vendor/bin/phpstan analyze -c phpstan.neon -l 7 src/; fi
    - if [[ ( ${TRAVIS_PHP_VERSION:0:3} == "7.2" ) && ( $TRAVIS_BRANCH == "master" ) ]]; then ./scripts/run_doctum_docs_on_travis.sh; fi

deploy:
  # How to deploy to S3: https://docs.travis-ci.com/user/deployment/s3/
  # master
  - provider: s3
    # To store these securely, here is how to encrypt: https://docs.travis-ci.com/user/encryption-keys/
    access_key_id:
      secure: "vAMX1aNVpxXrzSYKc2zjotsizyLPSrjvEqCsjRfadDh2CaIV+bF4EoRMFXDvyl/unb9GXxlJ5KTCgZ2cW+8HLsHxda4SYl0f03Du8/F4XbSa9JOyiwdzSW3Du/cpDxITIrZGMY/wKx3q6diGeKnX8+FjN3BAnIfdYCBtPeyisL/jjzjOxMh6xpDWADixej7sBZeRwpmL/PkQUickFabGCtfbxzdpH8l/dEd116D0eL/xivZqvAWTTB77nC/lWs1w6x+x5M7Q0Ch+AcSAzy8N4jFVJSMcxJMhqil4EoNjXFwBHNoMKKoJ8X9833js8l2gVfPRZ4mme26z9zwsSgRvDarrjH2/k5yzgMZV95QLsOqo7HADB2s3sRvAPEpl+13UO74LVpt5vfZ+6Z8rqhIZFGyVF8Qj3Glv9Bt2mJl8XF728lgdZMwNZZLg3dXqJQ9qzkAoub5VMAI8HtiaUaa3dHVW+nHKuCabzZtgcNgkRa/cr4F/h+gAUDzo1otDxWrjxTgoK5Grf8Nop5YPOe7oKuSIpOlOKh25ZVbFmldrTdfXzTqYbICGhSJYiu59rozViLszNCN/cRmfmrhhEcVZh+i55eODmVnThk/7jC6JPsUcBWcLq4Zc4BoUMiAUPhiHXtoTylgdERlcKQ7KznIvpkS1u8U3z1P8TSbu8eB43tU="
    secret_access_key:
      secure: "e4GO9KglnmjVwufPq5i0hzpCt40If7IKD6m3Qer3QeBal6x5blFoDQdXL7lqJ/WIdmeSF22p580SdTdlYRtEYulYaQqQs3MohggqtxRF2J268aSB32tTpwaa8WP1qpPv6Trzb93Tky2SwZOO1c82lI80/iONYaCRkc80J8gX2ebzHfhklCnN1xAQ0k68dFgJPitywtEwwatpgHnfvYFVe3B/rjdpUg1CItheWmazxIzwHc5evB2+vk0+KGWE2a7hosfiMdlgiKfcbFAV0J6UgP+qY4eAK0ekCEL3xB8DlpcjQaLYPQUK/9k0pkdUl+ma78a9XrikO+RR5Ul6unm42bC1ZV4BpCUFGLNw/T27dqT/Ot9laOKdWohR9DSmJxJ0Cd0MbxeeLlPobdu35ev5u0MuhKz8pJQoGPMXkT0KK2YIP6q7/dDd0ZIAHd6LN1nhMpXyR1ZqYoJxqhE0c5/V0HZ+I1NSeM+FQuig+qq8D0DwP8WNU0FprFFHjNBW7rOkxjYw1fMqHwWbtWXkj+SvxE3ktzycf9Ja66fMFcFferi3XtW01YEh7e2sFG5BhdwM3AMH5e0m3V0KhoCCckBXYn6thmg8PcKzICs2k3fRvhL2eJygb+d0AIZqarUY+gAegDAbP+6x/eOzcXGs+7q9tGMt9Pof+BVgKTmszJz9TIM="
    bucket: "rokka-io"
    region: "eu-central-1"
    skip_cleanup: true
    local_dir: doctum-output/build/
    on:
      branch: master
      php: "7.2"

cache:
  directories:
    - vendor
